userRegistration/registerApp/urls.py
from django.urls import path,include
from . import views

app_name = 'registerApp'

urlpatterns = [
    path('',views.index,name ="index"),
    path('register/',views.register,name ="register"),
    path('login/',views.userLogin,name ="login"),
    path('logout/',views.userLogout,name ="logout"),
]

userRegistration/userRegistration/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('registerApp.urls')),
]

userRegistration/registerApp/models.py
from django.db import models

# Create your models here.

userRegistration/registerApp/views.py
from django.shortcuts import render,redirect,reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
# Create your views here.
def index(request):
    return render(request,'registerApp/index.html')


def register(request):
    if request.method == "POST":
        username = request.POST['username']
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        pass1 = request.POST['pass1']
        myUser = User.objects.create_user(username=username,password=pass1)
        myUser.first_name = fname
        myUser.last_name = lname
        myUser.email = email
        myUser.save()
        messages.success(request,"You have been registerd successfully")
        return redirect('registerApp:login')
    return render(request,'registerApp/userRegister.html')

def userLogin(request):
    if request.method == "POST":
        username = request.POST['username']
        pass1 = request.POST['pass1']
        myUsr = authenticate(request,username=username,password=pass1)
        if myUsr is not None:
            login(request, myUsr)
            #return redirect('registerApp:index')
            return render(request,'registerApp/index.html',{'username':myUsr.username})
        else:
            messages.error(request,"Login Failed!!")
            return redirect('registerApp:login')
    return render(request,'registerApp/userLogin.html')

def userLogout(request):
    logout(request)
    return redirect('registerApp:index')

userRegistration/registerApp/templates/registerApp/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home Page</title>
  </head>
  <body>
    <h1>This is the home page</h1>
    {% if messages %}
      {% for message in messages %}
      <p>{{message}}</p>
      {% endfor %}
    {% endif %}
    {% if user.is_authenticated %}
      <h2>Hello {{username}}</h2>
      <a href="{% url 'registerApp:logout' %}"><input type="submit" name="logout" value="Log Out!"></a>
    {% else %}
    <a href="{% url 'registerApp:register' %}"><input type="submit" name="register" value="Sign Up!"></a>
    <a href="{% url 'registerApp:login' %}"><input type="submit" name="login" value="Log In!"></a>
    {% endif %}
  </body>
</html>

userRegistration/registerApp/templates/registerApp/userLogin.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Sign Up!</title>
  </head>
  <body>
    <h1>Sign up here !!</h1>
    {% if messages %}
      {% for message in messages %}
      <p>{{message}}</p>
      {% endfor %}
    {% endif %}
    <form action="/login/" method="post">
      {% csrf_token %}
      <label for="username">User Name :</label>
      <input type="text" name="username" placeholder="Enter username" required="True">
      <br><br>
      <label for="pass1">Password :</label>
      <input type="password" name="pass1" placeholder="Enter" required="True">
      <br><br>
      <!-- <a href="{% url 'registerApp:register' %}"><input type="submit" value="Submit!"></a> -->
      <input type="submit" value="Submit!">

    </form>
  </body>
</html>

userRegistration/registerApp/templates/registerApp/userRegister.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Sign Up!</title>
  </head>
  <body>
    <h1>Sign up here !!</h1>
    <form action="/register/" method="post">
      {% csrf_token %}
      <label for="username">User Name :</label>
      <input type="text" name="username" placeholder="Enter desired username" required="True">
      <br><br>
      <label for="fname">First Name :</label>
      <input type="text" name="fname" placeholder="Enter First Name" required="True">
      <br><br>
      <label for="lname">Last Name :</label>
      <input type="text" name="lname" placeholder="Enter Last Name" required="True">
      <br><br>
      <label for="email">Email id :</label>
      <input type="email" name="email" placeholder="Enter Email Id" required="True">
      <br><br>
      <label for="pass1">Password :</label>
      <input type="password" name="pass1" placeholder="Enter" required="True">
      <br><br>
      <!-- <a href="{% url 'registerApp:register' %}"><input type="submit" value="Submit!"></a> -->
      <input type="submit" value="Submit!">

    </form>
  </body>
</html>